services:
    api: 
      container_name: homelab_backend
      
      build: 
        context: ./back-end
        dockerfile: Dockerfile.development
      ports:
        - 8005:8005
      volumes:
        - ./back-end:/app
      networks:
        - script-network

networks:
    script-network:
      external:
        name: script-network