services:
    api: 
      container_name: homelab_backend
      
      build: 
        context: ./back-end
        dockerfile: Dockerfile.development
      ports:
        - 8005:8005
      volumes:
        - ./back-end:/app
      networks:
        - app-network

    app:
      container_name: homelab_frontend

      build:
        context: ./front-end
        dockerfile: Dockerfile.development
      environment:
        - WDS_SOCKET_PORT=0
      ports:
        - 3008:3000
      volumes:
        - ./front-end:/usr/src/app
      networks:
        - app-network

    postgres:
      image: postgres:13.1
      command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
      container_name: homelab_db
      hostname: homelab_postgres
      environment:
          POSTGRES_PASSWORD: 'P0stgr3s'
      ports:
          - 25432:5432
      volumes:
          - ./volumes/postgres-data:/var/lib/postgresql/data  
      networks:
          - app-network

networks:
    app-network:
      driver: bridge